### ISSUE TITLE
Gestion des versions avec les releases de Git et gestion des Nuget

### ISSUE THREAD

**Issue by mdeslauriers-sigmund** [sigmundftw/EnhancedDictionaryEditor#18]
S'assurer de taguer une release Git pour chaque version du code pour laquelle on produit un Nuget.

Voir si on aurait un moyen pour automatiser la création et l'upload d'une nouvelle version de nuget lors d'une nouvelle release

**Comment by leddt** [comment]
https://dev.azure.com/sigmundftw/EnhancedDictionaryEditor/_release?view=mine&definitionId=1

**Comment by DTONeill** [comment]
Déjà en place https://dev.azure.com/sigmundftw/EnhancedDictionaryEditor/_release?view=mine&definitionId=1
